name: 'agro_meteo'
version: '1.0.0'
config-version: 2

profile: 'agro_meteo'

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  agro_meteo:
    staging:
      +materialized: view
    marts:
      +materialized: table
